// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtBnL_rGYlesXjo5GliuyPVzeC8GLPbJI',
    appId: '1:488002303012:web:fb52d7952f62f6ef1854b1',
    messagingSenderId: '488002303012',
    projectId: 'diablo-immortal-character',
    authDomain: 'diablo-immortal-character.firebaseapp.com',
    databaseURL: 'https://diablo-immortal-character-default-rtdb.firebaseio.com',
    storageBucket: 'diablo-immortal-character.appspot.com',
    measurementId: 'G-VHGP1MVW57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFJyx00BbDctiegq7nj9FuV85nq-bzBAI',
    appId: '1:488002303012:android:10f009cc42af9b291854b1',
    messagingSenderId: '488002303012',
    projectId: 'diablo-immortal-character',
    databaseURL: 'https://diablo-immortal-character-default-rtdb.firebaseio.com',
    storageBucket: 'diablo-immortal-character.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw145PClQUNpjr1x8TsG5kp3rR30Ru4Wg',
    appId: '1:488002303012:ios:637f7a85359f3b571854b1',
    messagingSenderId: '488002303012',
    projectId: 'diablo-immortal-character',
    databaseURL: 'https://diablo-immortal-character-default-rtdb.firebaseio.com',
    storageBucket: 'diablo-immortal-character.appspot.com',
    iosBundleId: 'com.example.learningFlutterVsc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw145PClQUNpjr1x8TsG5kp3rR30Ru4Wg',
    appId: '1:488002303012:ios:637f7a85359f3b571854b1',
    messagingSenderId: '488002303012',
    projectId: 'diablo-immortal-character',
    databaseURL: 'https://diablo-immortal-character-default-rtdb.firebaseio.com',
    storageBucket: 'diablo-immortal-character.appspot.com',
    iosBundleId: 'com.example.learningFlutterVsc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtBnL_rGYlesXjo5GliuyPVzeC8GLPbJI',
    appId: '1:488002303012:web:0a8f17af0becb6c51854b1',
    messagingSenderId: '488002303012',
    projectId: 'diablo-immortal-character',
    authDomain: 'diablo-immortal-character.firebaseapp.com',
    databaseURL: 'https://diablo-immortal-character-default-rtdb.firebaseio.com',
    storageBucket: 'diablo-immortal-character.appspot.com',
    measurementId: 'G-9S0W2K9EWT',
  );

}